### ISSUE TITLE
Config not found

### ISSUE THREAD

**Issue by Ulyanov-programmer** [Cascades-CSS/CSS-to-HTML#20] opened 2024-09-25 07:34 UTC
_Hello!_

In the process of using your library, I found an error that did not allow me to use it.

When importing the function:
```js
import { cssToHtml } from 'css-to-html';
```
An error appears with content like:
```shell
"path_to_this/Config" not found (404)
```
This error appears both when I use the library separately (in `node.js`) and when I call it in the browser.

Perhaps you should specify the path to the imported file more precisely, because you have it, but the path to it is incorrect.

**Comment by Gigabyte5671** [comment] 2024-09-25 10:44
Hi, thanks for letting me know about this!

This package relies on some browser-only JS features, so it currently doesn't work in Node.  
_(I've [added a note to the readme](https://github.com/Cascades-CSS/CSS-to-HTML/commit/2358ea592fb26a445fb1f49c2c9f9a93d56c7f71) to let others know about this limitation. Thanks.)_

Regardless, I'll be able to take a closer look at your issue in a few hours. In the mean time, can you please share the steps you took / the build system you're using to run this in your browser?

**Comment by Ulyanov-programmer** [comment] 2024-09-25 11:44
I tried this:

0. I downloaded your library from `npm` and unpacked the dist folder locally.
1. I entered the following code in the `.html` file:
```html
<script type="module">
  import { cssToHtml } from 'path_to_dist_of_css-to-html/index.js'

  // From a CSS string:
  const css = 'p { color: purple; }'
  cssToHtml(css).then((html) => {
    console.log(html)
  })
</script>
```
2. I ran this file in the browser and got this error seen in the console:
```
GET http://localhost:1243/assets/cssToHtml/Config net::ERR_ABORTED 404 (Not Found)
```

**Comment by Gigabyte5671** [comment] 2024-09-25 20:23
Many thanks!

I was able to reproduce the issue. Turns out there was a typo in the Config module's import path.  
Fixed with 1d07020.

Please let me know if you have any more issues.

**Closed by Gigabyte5671** 2024-09-25 20:23 UTC
Labels: bug

**Comment by Ulyanov-programmer** [comment] 2024-09-26 08:38
You definitely shouldn't rush into releases, because I found another bug!

I did the [same thing](https://github.com/Cascades-CSS/CSS-to-HTML/issues/20#issuecomment-2373850794), but got another error after launching:
```
Uncaught TypeError: Failed to resolve module specifier "css-selector-parser". Relative references must start with either "/", "./", or "../".
```


Apparently, this is happening here: https://github.com/Cascades-CSS/CSS-to-HTML/blob/3e92f9d38544d649188227800c270eee3b313b10/src/Generator.ts#L1
This string is **saved** after compilation, which can be seen in the `npm` version.

If the library worked within the package manager, this would not be a mistake, but since it is supposed to work in the browser, he complains.

**Comment by Ulyanov-programmer** [comment] 2024-09-26 08:40
In general, for the future: before closing an issue, ask its creator if it works for him.
This will protect you from many errors that could get into production.

**Comment by Ulyanov-programmer** [comment] 2024-09-26 09:13
Yes, it is definitely worth adding a mention of this - it is not obvious from the description of the library at all.
Thank you for your prompt response!

**Comment by Gigabyte5671** [comment] 2024-09-28 03:55
Hi again!

I've just added support for using CSS-to-HTML as a static script with version [0.8.0](https://github.com/Cascades-CSS/CSS-to-HTML/releases/tag/v0.8.0).

**Comment by Ulyanov-programmer** [comment] 2024-09-28 08:03
Great! But I don't really need it, because I am the developer of an alternative solution [css2html](https://www.npmjs.com/package/css2html ) (I only found out about the existence of your library when I wanted to publish my package, as it turned out, under your name), therefore, I will limit my help. :]

**Comment by Gigabyte5671** [comment] 2024-09-28 08:43
All good! Good luck with your library :)
